### ISSUE TITLE
Can't start up system after compile the kernel

### ISSUE THREAD

**Issue by GaryLee1101** [RutgersCSSystems/FusionFS#1]
Hello, I'd like to employ the FusionFS on my server for some tests. My server is equipped with an Intel E5-2640, 256GB DRAM, and an HDD.
But the system can't startup in kernel 4.8.12 after I compile the kernel by "$BASE/scripts/compile_kernel_install.sh".
The error is "fat-fs (sda1) io charset iso8859-1 not found", and the system starts up in emergency mode.
I tried some solutions such as fsck and depmod, but useless.
Could you provide how to eliminate this error? Thanks!

**Comment by glock42** [comment]
I haven't had this issue before. But could you check the `/boot/grub/grub.cfg` file to make sure that `kernel 4.8.12` is the first boot entry? And make sure the kernel is compiled and installed successfully. Thanks.

**Comment by glock42** [comment]
Issue closed, if there are any more questions, feel free to reopen.
